name = "link-scraper"
main = "link-scraper.js"
compatibility_date = "2024-12-18"

# Uncomment to use a custom domain
# routes = [
#   { pattern = "link-scraper.yourdomain.com", custom_domain = true }
# ]
